---

## need to add environment for CPU specific parameters 
- name: clean kernel build environment
  make: 
    chdir: "{{ kernel_build_path }}"
    target: mrproper
 
- name: copy config to build path
  template: 
    src: "config.j2"
    dest: "{{ kernel_build_path }}/.config"
 
- name: accept default parameters for new kernel options
  make: 
    chdir: "{{ kernel_build_path }}"
    target: olddefconfig
  environment: 
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    CFLAGS: "-O2 -march=znver1"
 
- name: get patches to apply
  find: 
    paths: "files"
  register: patches
  
- name: inject patches if they should be applied
  patch: 
    src: "{{ item.path }}"
    basedir: "{{ kernel_build_path }}"
    strip: 1
  loop: "{{ patches.files }}"

# specify threads to use   
- name: compile kernel
  make:
    chdir: "{{ kernel_build_path }}"
    target: "_all"
  environment: 
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    CFLAGS: "-O2 -march=znver1"

- name: compile kernel modules
  make:
     chdir: "{{ kernel_build_path }}"
     target: "modules_install"
  become: yes
  environment: 
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    CFLAGS: "-O2 -march=znver1"

- name: copy kernel to boot directory
  copy: 
    src: "{{ kernel_build_path }}/arch/x86_64/boot/bzImage"
    dest: "/boot/vmlinuz-linux{{ latest_available_kernel  | replace('.', '-') }}{{ kernel_substring }}"
  become: yes

- name: create and copy own mkinitcpio config to target
  template:
    src: "mkinitcpio.conf.j2"
    dest: "{{ kernel_build_path }}/mkinitcpio.conf"

- name: create and copy mkinitcpio preset to target
  template:
    src: "mkinitcpio-linux-preset.j2"
    dest: "/etc/mkinitcpio.d/linux{{ latest_available_kernel  | replace('.', '-')  }}{{ kernel_substring }}.preset"
  become: yes

- name: create initram image
  command: mkinitcpio -c {{ kernel_build_path }}/mkinitcpio.conf -p linux{{ latest_available_kernel  | replace('.', '-')  }}{{ kernel_substring }}
  become: yes
  
- name: update grub boot config if bootloader is grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
  become: yes
 
 
