galaxy_info:
  author: Simon Lichtenauer
  description:  This role downloads, validates and extracts the requested linux kernel version

  license: GPL-2.0-or-later

  min_ansible_version: 2.9

  platforms:
    - name: arch
      versions:
        - all
